# Generated by Django 5.2.7 on 2026-09-26 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0012_userprofile_can_create_projects_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBreachIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("nature_and_scope", models.TextField()),
                ("affected_data_categories", models.TextField()),
                (
                    "estimated_affected_principals",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("containment_actions", models.TextField(blank=True)),
                ("remediation_steps", models.TextField(blank=True)),
                ("board_notified", models.BooleanField(default=False)),
                (
                    "board_notification_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("board_reference_id", models.CharField(blank=True, max_length=100)),
                ("principals_notified", models.BooleanField(default=False)),
                (
                    "principals_notification_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("resolved", "Resolved"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="DataPrincipalNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominee_name", models.CharField(max_length=150)),
                ("nominee_email", models.EmailField(max_length=254)),
                ("nominee_phone", models.CharField(blank=True, max_length=25)),
                ("relationship", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomination",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("essential_service", "Account & Core Task Management"),
                            (
                                "email_notifications",
                                "Task Reminders, Comments & Alert Emails",
                            ),
                            ("ai_assistant", "AI Task Breakdown & Roadmap Planning"),
                            (
                                "product_updates",
                                "Platform Announcements & Feature Updates",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Consent Granted"),
                            ("withdrawn", "Consent Withdrawn"),
                        ],
                        db_index=True,
                        default="granted",
                        max_length=20,
                    ),
                ),
                (
                    "notice_version",
                    models.CharField(default="1.0-2025-DPDP", max_length=30),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("channel", models.CharField(default="web_app", max_length=50)),
                (
                    "granted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpdp_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "status"],
                        name="todo_consen_user_id_6fc94b_idx",
                    ),
                    models.Index(
                        fields=["user", "-granted_at"],
                        name="todo_consen_user_id_137b24_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Pseudonymized user reference if user deleted",
                        max_length=150,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("resource", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="todo_privac_action_3cf0fa_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="todo_privac_user_id_2f619f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivacyGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("access", "Access to Personal Data (Section 11)"),
                            (
                                "correction",
                                "Correction / Updation of Personal Data (Section 12)",
                            ),
                            ("erasure", "Erasure / Account Deletion (Section 12(3))"),
                            ("consent", "Consent / Withdrawal Issue (Section 6)"),
                            (
                                "security",
                                "Security / Data Protection Concern (Section 8)",
                            ),
                            ("other", "General Data Protection Grievance"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted / Awaiting Review"),
                            ("in_review", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected / Ineligible"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("statutory_deadline", models.DateField(db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket_number"], name="todo_privac_ticket__67bce9_idx"
                    ),
                    models.Index(
                        fields=["status", "statutory_deadline"],
                        name="todo_privac_status_2cc9a6_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="todo_privac_user_id_5f1abf_idx",
                    ),
                ],
            },
        ),
    ]
